name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    name: Build game and publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      BUILD_PLATFORM: StandaloneWindows64
      BUILD_PATH: build
      UNITY_VERSION: 6000.2.7f2
      # Если тег ниже не существует в реестре — попробуйте вариант без "ubuntu-":
      # IMAGE_TAG: 6000.2.7f2-windows-mono-3.1
      IMAGE_TAG: ubuntu-6000.2.7f2-windows-mono-3.1

    steps:
      - name: Check UNITY_LICENSE secret
        run: |
          if [ -z "${{ secrets.UNITY_LICENSE }}" ]; then
            echo "::error::UNITY_LICENSE secret is not set. Add your ULF text to repository secret UNITY_LICENSE."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/unity3d
            ~/.local/share/unity3d
          key: unity-${{ runner.os }}-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}

      - name: Build project (Windows x64)
        uses: game-ci/unity-builder@v4
        env:
          # Личная (Personal) лицензия — только ULF:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ env.BUILD_PLATFORM }}
          unityVersion: ${{ env.UNITY_VERSION }}
          # Обход некорректной сборки имени образа
          customImage: unityci/editor:${{ env.IMAGE_TAG }}
          allowDirtyBuild: true
          # projectPath по умолчанию "."

      - name: Archive build
        id: archive
        shell: bash
        run: |
          VERSION=$(sed -n 's/^bundleVersion: //p' ProjectSettings/ProjectSettings.asset)
          if [ -z "$VERSION" ]; then
            VERSION="${GITHUB_RUN_NUMBER}"
          fi
          RELEASE_NAME="EscapeFromCave-${VERSION}-${{ env.BUILD_PLATFORM }}"
          ZIP_PATH="${RELEASE_NAME}.zip"
          echo "release_name=${RELEASE_NAME}" >> "$GITHUB_OUTPUT"
          echo "zip_path=${ZIP_PATH}" >> "$GITHUB_OUTPUT"
          cd "${{ env.BUILD_PATH }}/${{ env.BUILD_PLATFORM }}"
          zip -r "../../${ZIP_PATH}" .

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.archive.outputs.release_name }}
          name: ${{ steps.archive.outputs.release_name }}
          artifacts: ${{ steps.archive.outputs.zip_path }}
          artifactContentType: application/zip
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
